DEFAULT_SITE:
  DEFAULT_GETEKEEPER:
    DEFAULT_ENTRY:
      num_factories: 2
      attrs:
        ENABLE_IPV6:
          type: expr
        GLEXEC_BIN:
          glidein_publish: False
          value: NONE
        GLIDEIN_CMSSite:
          job_publish: True
        GLIDEIN_Country:
          value: US
        GLIDEIN_CPUS:
          glidein_publish: False
          job_publish: True
          value: 1
        GLIDEIN_Is_Preemptable:
          type: expr
        GLIDEIN_Job_Max_Time:
          type: int
        GLIDEIN_MaxMemMBs:
          type: int
          value: 2500
        GLIDEIN_Max_Walltime:
          glidein_publish: False
          type: int
        GLIDEIN_REQUIRED_OS:
          value: rhel6
        GLIDEIN_Site:
          job_publish: True
        GLIDEIN_Supported_VOs:
          glidein_publish: False
          value: OSGVO
        GLIDEIN_ResourceName:
          job_publish: True
        GLIDEIN_Retire_Time:
          type: int
          glidein_publish: False
        GLIDEIN_Retire_Time_Spread:
          type: int
      enabled: True
      limits:
        entry:
          glideins: 10000 # absolute number
          held: 10 # percentages
          idle: 20 # percentages
        frontend:
          glideins: 5000 # absolute number
          held: 10 # percentages
          idle: 20 # percentages
      submission_speed: normal
      trust_domain: grid
      auth_method: scitoken
      work_dir: OSG
      proxy_url: OSG
      verbosity: std
      comment: "Entry automatically generated"
